name: kuber
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.6.1


dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  window_manager: ^0.4.3
  sizer: ^3.0.5
  intl: ^0.19.0
  fluttertoast: ^8.2.10
  flutter_bloc: ^9.0.0
  socket_io_client: ^3.0.2
  barcode: ^2.2.8
  flutter_svg: ^2.0.17
  device_info_plus: ^11.2.1
  path_provider: ^2.1.5
  image: 4.5.2
  device_preview_plus: ^2.2.4
  flutter_thermal_printer: ^1.0.1
  http: ^1.3.0
  flutter_secure_storage: ^9.2.4
  shared_preferences: ^2.4.0
  pdf: ^3.11.2
  barcode_widget: ^2.0.4
  # blue_thermal_printer: ^1.2.3
  printing: ^5.14.0
  calendar_date_picker2: ^1.1.8
  # flutter_html_to_pdf: ^0.7.0
 
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  


flutter_launcher_icons:
  # android: "launcher_icon"
  # ios: true
  # image_path: "assets/logo/kuber_logo.png"
  # min_sdk_android: 21 # android min sdk min:16, default 21
  # web:
  #   generate: true
  #   image_path: "path/to/image.png"
  #   background_color: "#hexcode"
  #   theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/logo/kuber_logo.png"
    icon_size: 48 # min:48, max:256, default: 48
  # macos:
  #   generate: true
  #   image_path: "path/to/image.png"


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.`
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/logo/
    - assets/bg/
    - assets/duskadam/
    - assets/duskadam/colored/
    - assets/pdf/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
